package com.explitech.jxc.model;

public class Customer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer customerTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String customerTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.customer_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.company_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.telephone
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.address
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.email
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.QQ
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String qq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer.acount
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String acount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_id
     *
     * @return the value of customer.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_id
     *
     * @param customerId the value for customer.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_type_id
     *
     * @return the value of customer.customer_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getCustomerTypeId() {
        return customerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_type_id
     *
     * @param customerTypeId the value for customer.customer_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCustomerTypeId(Integer customerTypeId) {
        this.customerTypeId = customerTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_type_name
     *
     * @return the value of customer.customer_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getCustomerTypeName() {
        return customerTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_type_name
     *
     * @param customerTypeName the value for customer.customer_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCustomerTypeName(String customerTypeName) {
        this.customerTypeName = customerTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.customer_name
     *
     * @return the value of customer.customer_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.customer_name
     *
     * @param customerName the value for customer.customer_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.company_name
     *
     * @return the value of customer.company_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.company_name
     *
     * @param companyName the value for customer.company_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.telephone
     *
     * @return the value of customer.telephone
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.telephone
     *
     * @param telephone the value for customer.telephone
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.address
     *
     * @return the value of customer.address
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.address
     *
     * @param address the value for customer.address
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.QQ
     *
     * @return the value of customer.QQ
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.QQ
     *
     * @param qq the value for customer.QQ
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer.acount
     *
     * @return the value of customer.acount
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getAcount() {
        return acount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer.acount
     *
     * @param acount the value for customer.acount
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setAcount(String acount) {
        this.acount = acount;
    }
}