package com.explitech.jxc.model;

public class Dictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.item_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.category
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.item_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dictionary.parent_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.item_id
     *
     * @return the value of dictionary.item_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.item_id
     *
     * @param itemId the value for dictionary.item_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.category
     *
     * @return the value of dictionary.category
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.category
     *
     * @param category the value for dictionary.category
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.item_name
     *
     * @return the value of dictionary.item_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.item_name
     *
     * @param itemName the value for dictionary.item_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dictionary.parent_id
     *
     * @return the value of dictionary.parent_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dictionary.parent_id
     *
     * @param parentId the value for dictionary.parent_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }
}