package com.explitech.jxc.model;

import java.util.Date;
import java.util.List;

public class Form {
		
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_type_Id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer formTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.form_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String formTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Float total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.input_date
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Date inputDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_id
     *
     * @return the value of form.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_id
     *
     * @param formId the value for form.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_type_Id
     *
     * @return the value of form.form_type_Id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getFormTypeId() {
        return formTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_type_Id
     *
     * @param formTypeId the value for form.form_type_Id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setFormTypeId(Integer formTypeId) {
        this.formTypeId = formTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.form_type_name
     *
     * @return the value of form.form_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getFormTypeName() {
        return formTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.form_type_name
     *
     * @param formTypeName the value for form.form_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setFormTypeName(String formTypeName) {
        this.formTypeName = formTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.total
     *
     * @return the value of form.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.total
     *
     * @param total the value for form.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setTotal(Float total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.input_date
     *
     * @return the value of form.input_date
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.input_date
     *
     * @param inputDate the value for form.input_date
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form.customer_id
     *
     * @return the value of form.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form.customer_id
     *
     * @param customerId the value for form.customer_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
   
    
}