package com.explitech.jxc.model;

public class FormDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_detail.form_detail_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer formDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_detail.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer formId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_detail.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_detail.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column form_detail.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Float total;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_detail.form_detail_id
     *
     * @return the value of form_detail.form_detail_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getFormDetailId() {
        return formDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_detail.form_detail_id
     *
     * @param formDetailId the value for form_detail.form_detail_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setFormDetailId(Integer formDetailId) {
        this.formDetailId = formDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_detail.form_id
     *
     * @return the value of form_detail.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getFormId() {
        return formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_detail.form_id
     *
     * @param formId the value for form_detail.form_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setFormId(Integer formId) {
        this.formId = formId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_detail.product_id
     *
     * @return the value of form_detail.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_detail.product_id
     *
     * @param productId the value for form_detail.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_detail.quantity
     *
     * @return the value of form_detail.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_detail.quantity
     *
     * @param quantity the value for form_detail.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column form_detail.total
     *
     * @return the value of form_detail.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Float getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column form_detail.total
     *
     * @param total the value for form_detail.total
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setTotal(Float total) {
        this.total = total;
    }
}