package com.explitech.jxc.model;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer productTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.description
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Float price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_color_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer productColorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_color_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private String productColorName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_id
     *
     * @return the value of product.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_id
     *
     * @param productId the value for product.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_name
     *
     * @return the value of product.product_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_name
     *
     * @param productName the value for product.product_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type_id
     *
     * @return the value of product.product_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type_id
     *
     * @param productTypeId the value for product.product_type_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_type_name
     *
     * @return the value of product.product_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_type_name
     *
     * @param productTypeName the value for product.product_type_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.description
     *
     * @return the value of product.description
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.description
     *
     * @param description the value for product.description
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Float getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setPrice(Float price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_color_id
     *
     * @return the value of product.product_color_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getProductColorId() {
        return productColorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_color_id
     *
     * @param productColorId the value for product.product_color_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductColorId(Integer productColorId) {
        this.productColorId = productColorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_color_name
     *
     * @return the value of product.product_color_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public String getProductColorName() {
        return productColorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_color_name
     *
     * @param productColorName the value for product.product_color_name
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductColorName(String productColorName) {
        this.productColorName = productColorName;
    }
}