package com.explitech.jxc.model;

public class Store {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    private Integer quantity;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.product_id
     *
     * @return the value of store.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.product_id
     *
     * @param productId the value for store.product_id
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.quantity
     *
     * @return the value of store.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.quantity
     *
     * @param quantity the value for store.quantity
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
}