package com.explitech.jxc.dao;

import com.explitech.jxc.model.FormDetail;
import com.explitech.jxc.model.FormDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int countByExample(FormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int deleteByExample(FormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int deleteByPrimaryKey(Integer formDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int insert(FormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int insertSelective(FormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    List<FormDetail> selectByExample(FormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    FormDetail selectByPrimaryKey(Integer formDetailId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByExampleSelective(@Param("record") FormDetail record, @Param("example") FormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByExample(@Param("record") FormDetail record, @Param("example") FormDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByPrimaryKeySelective(FormDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form_detail
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByPrimaryKey(FormDetail record);
}