package com.explitech.jxc.dao;

import com.explitech.jxc.model.Form;
import com.explitech.jxc.model.FormExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FormMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int countByExample(FormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int deleteByExample(FormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int deleteByPrimaryKey(Integer formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int insert(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int insertSelective(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    List<Form> selectByExample(FormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    Form selectByPrimaryKey(Integer formId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByExampleSelective(@Param("record") Form record, @Param("example") FormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByExample(@Param("record") Form record, @Param("example") FormExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByPrimaryKeySelective(Form record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table form
     *
     * @mbggenerated Tue Aug 14 10:41:28 CST 2012
     */
    int updateByPrimaryKey(Form record);
}